/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import dao.CompteDAO;
import dao.UtilisateurDAO;
import models.Utilisateurs;
import utils.UtilsFonction;
import java.util.List;
import javax.swing.JOptionPane;
import dao.TransactionDAO;
import models.Comptes;
/**
 *
 * @author SOW
 */
public class AdminFormulaire extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminFormulaire.class.getName());
     private UtilisateurDAO userDAO;
     private TransactionDAO transactionDAO;
     private CompteDAO compteDAO;
     private Utilisateurs utilisateurSelectionne;
    
    /**
     * Creates new form AdminFormulaire
     */
    public AdminFormulaire() {
        initComponents();
        
        userDAO = new UtilisateurDAO();
        transactionDAO = new TransactionDAO();
        compteDAO = new CompteDAO();

chargerUtilisateurs();
chargerStatistiques();
    }
     private void chargerUtilisateurs() {

        List<Utilisateurs> utilisateurs =
                userDAO.allUtilisateurs();

        UtilsFonction.displayDataInTable(
                utilisateurs,
                jTable1
        );
        
        
}
     private void chargerStatistiques() {

    List<Utilisateurs> utilisateurs =
            userDAO.allUtilisateurs();

    int nbUsers = utilisateurs.size();
    int nbGestionnaires = 0;
    int nbCaissiers = 0;

    for (Utilisateurs u : utilisateurs) {

        if (u.getRole().equals("gestionnaire")) {
            nbGestionnaires++;
        }

        if (u.getRole().equals("caissier")) {
            nbCaissiers++;
        }
    }

    int nbTransactions =
            transactionDAO.allTransaction().size();
    java.math.BigDecimal soldeCourant =
        java.math.BigDecimal.ZERO;

java.math.BigDecimal soldeEpargne =
        java.math.BigDecimal.ZERO;

for(Comptes c : compteDAO.allComptes()){

    if(c.getTypeCompte().equals("courant")){

        soldeCourant =
                soldeCourant.add(
                        c.getSolde());
    }

    if(c.getTypeCompte().equals("epargne")){

        soldeEpargne =
                soldeEpargne.add(
                        c.getSolde());
    }
}

    lblUsers.setText(
            "Utilisateurs : " + nbUsers);

    lblGestionnaires.setText(
            "Gestionnaires : " + nbGestionnaires);

    lblCaissiers.setText(
            "Caissiers : " + nbCaissiers);

    lblTransactions.setText(
            "Transactions : " + nbTransactions);
    
    
lblSoldeCourant.setText(
        "Solde Courant : "
        + soldeCourant);

lblSoldeEpargne.setText(
        "Solde Epargne : "
        + soldeEpargne);

lblTotalDepot.setText(
        "Total Dépôts : "
        + transactionDAO.totalDepot());

lblTotalRetrait.setText(
        "Total Retraits : "
        + transactionDAO.totalRetrait());
lblTotalFrais.setText(
        "Total Frais : "
        + transactionDAO.totalFrais());

}
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jColorChooser3 = new javax.swing.JColorChooser();
        gestionnaire_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        activer_btn = new javax.swing.JButton();
        lblUsers = new javax.swing.JLabel();
        lblGestionnaires = new javax.swing.JLabel();
        lblCaissiers = new javax.swing.JLabel();
        lblTransactions = new javax.swing.JLabel();
        desactiver_btn = new javax.swing.JButton();
        caissier_btn = new javax.swing.JButton();
        lblSoldeCourant = new javax.swing.JLabel();
        lblSoldeEpargne = new javax.swing.JLabel();
        lblTotalDepot = new javax.swing.JLabel();
        lblTotalRetrait = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblTotalFrais = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gestionnaire_btn.setText("CREER GESTIONNAIRE");
        gestionnaire_btn.addActionListener(this::gestionnaire_btnActionPerformed);

        jLabel1.setText("TABLEAU DE BORD ADMINISTRATEUR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        activer_btn.setText("ACTIVER");
        activer_btn.addActionListener(this::activer_btnActionPerformed);

        lblUsers.setText("Utilisateurs       : ");

        lblGestionnaires.setText("Gestionnaires   :  ");

        lblCaissiers.setText("Caissiers     : ");

        lblTransactions.setText("Transactions  :    ");

        desactiver_btn.setText("DESACTIVER");
        desactiver_btn.addActionListener(this::desactiver_btnActionPerformed);

        caissier_btn.setText("CREER CAISSIER");
        caissier_btn.addActionListener(this::caissier_btnActionPerformed);

        lblSoldeCourant.setText("solde courant :");

        lblSoldeEpargne.setText("Solde Epargne :");

        lblTotalDepot.setText("Total Dépôts :");

        lblTotalRetrait.setText("Total Retraits : ");

        jButton1.setText("VOIR TRANSACTIONS");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        lblTotalFrais.setText("Total Frais :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTransactions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCaissiers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGestionnaires, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(lblUsers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gestionnaire_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addGap(53, 53, 53))
                            .addComponent(caissier_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSoldeCourant, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotalDepot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSoldeEpargne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTotalRetrait, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTotalFrais, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(desactiver_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(activer_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoldeCourant))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblGestionnaires, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblSoldeEpargne)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblCaissiers, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblTotalDepot)))
                        .addGap(5, 5, 5)
                        .addComponent(lblTotalRetrait)
                        .addGap(9, 9, 9)
                        .addComponent(lblTransactions)
                        .addGap(3, 3, 3)
                        .addComponent(lblTotalFrais)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gestionnaire_btn)
                            .addComponent(activer_btn))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caissier_btn)
                            .addComponent(desactiver_btn))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caissier_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caissier_btnActionPerformed
        // TODO add your handling code here:
    new Inscription("caissier").setVisible(true);
    }//GEN-LAST:event_caissier_btnActionPerformed

    private void gestionnaire_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionnaire_btnActionPerformed
        // TODO add your handling code here:
        new Inscription("gestionnaire").setVisible(true);
    }//GEN-LAST:event_gestionnaire_btnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int ligne = jTable1.getSelectedRow();

if (ligne >= 0) {

    Integer id = Integer.valueOf(
            jTable1.getValueAt(ligne, 0).toString()
    );

    utilisateurSelectionne = userDAO.findById(id);

}
    }//GEN-LAST:event_jTable1MouseClicked

    private void desactiver_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desactiver_btnActionPerformed
        // TODO add your handling code here:
        if (utilisateurSelectionne == null) {

    JOptionPane.showMessageDialog(
            this,
            "Sélectionnenrel benn  utilisateur"
    );
    return;
}

utilisateurSelectionne.setActif(false);

userDAO.updateUser(utilisateurSelectionne);

chargerUtilisateurs();

JOptionPane.showMessageDialog(
        this,
        "Utilisateur bi  désactivé nagne ko "
);
    }//GEN-LAST:event_desactiver_btnActionPerformed

    private void activer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activer_btnActionPerformed
        // TODO add your handling code here:
        if (utilisateurSelectionne == null) {

    JOptionPane.showMessageDialog(
            this,
            "Sélectionnenel benn utilisateur"
    );
    return;
}

utilisateurSelectionne.setActif(true);

userDAO.updateUser(utilisateurSelectionne);

chargerUtilisateurs();

JOptionPane.showMessageDialog(
        this,
        "Utilisateur bi  activé nagne ko "
);
    }//GEN-LAST:event_activer_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ListeTransactionsForm().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminFormulaire().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activer_btn;
    private javax.swing.JButton caissier_btn;
    private javax.swing.JButton desactiver_btn;
    private javax.swing.JButton gestionnaire_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JColorChooser jColorChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCaissiers;
    private javax.swing.JLabel lblGestionnaires;
    private javax.swing.JLabel lblSoldeCourant;
    private javax.swing.JLabel lblSoldeEpargne;
    private javax.swing.JLabel lblTotalDepot;
    private javax.swing.JLabel lblTotalFrais;
    private javax.swing.JLabel lblTotalRetrait;
    private javax.swing.JLabel lblTransactions;
    private javax.swing.JLabel lblUsers;
    // End of variables declaration//GEN-END:variables
}
