/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.UtilisateurDAO;
import models.Utilisateurs;
import utils.UtilsFonction;
import javax.swing.JOptionPane;
/**
 *
 * @author SOW
 */
public class ChangerMotDePasseForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChangerMotDePasseForm.class.getName());
  private Utilisateurs utilisateur;
  private UtilisateurDAO userDAO;
    /**
     * Creates new form ChangerMotDePasseForm
     */
    public ChangerMotDePasseForm() {
        initComponents();
    }
    public ChangerMotDePasseForm(Utilisateurs utilisateur) {

    initComponents();

    this.utilisateur = utilisateur;

    userDAO = new UtilisateurDAO();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        modifier_btn = new javax.swing.JButton();
        ancienPassword_txt = new javax.swing.JPasswordField();
        nouveauPassword_txt = new javax.swing.JPasswordField();
        confirmationPassword_txt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ancien mot de passe");

        jLabel2.setText("Nouveau mot de passe");

        jLabel3.setText("Confirmation");

        modifier_btn.setText("Modifier Le Mot de Passe");
        modifier_btn.addActionListener(this::modifier_btnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ancienPassword_txt)
                            .addComponent(nouveauPassword_txt)
                            .addComponent(confirmationPassword_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(modifier_btn)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ancienPassword_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nouveauPassword_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmationPassword_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(modifier_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifier_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifier_btnActionPerformed
        // TODO add your handling code here:
        String ancienPassword =
        String.valueOf(ancienPassword_txt.getPassword());

String nouveauPassword =
        String.valueOf(nouveauPassword_txt.getPassword());

String confirmation =
        String.valueOf(confirmationPassword_txt.getPassword());

if (!UtilsFonction.decrypt(utilisateur.getPassword())
        .equals(ancienPassword)) {

    JOptionPane.showMessageDialog(
            this,
            "Ancien mot de passe incorrect"
    );

    return;
}

if (!nouveauPassword.equals(confirmation)) {

    JOptionPane.showMessageDialog(
            this,
            "Les mots de passe ne correspondent pas"
    );

    return;
}

if (nouveauPassword.length() < 8) {

    JOptionPane.showMessageDialog(
            this,
            "Minimum 8 caractères"
    );

    return;
}

if (!nouveauPassword.matches(".*[@#$%^&+=!].*")) {

    JOptionPane.showMessageDialog(
            this,
            "Ajoutez un caractère spécial"
    );

    return;
}

utilisateur.setPassword(
        UtilsFonction.encrypt(nouveauPassword));

utilisateur.setPremiereConnexion(false);

userDAO.updatePassword(utilisateur);

JOptionPane.showMessageDialog(
        this,
        "Mot de passe modifié avec succès.\nVeuillez vous reconnecter."
);

new Connexion().setVisible(true);

this.dispose();
    }//GEN-LAST:event_modifier_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ChangerMotDePasseForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ancienPassword_txt;
    private javax.swing.JPasswordField confirmationPassword_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton modifier_btn;
    private javax.swing.JPasswordField nouveauPassword_txt;
    // End of variables declaration//GEN-END:variables
}
