/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.UtilisateurDAO;
import enums.Role;
import java.util.List;
import javax.swing.JOptionPane;
import models.Utilisateurs;
import utils.UtilsFonction;

/**
 *
 * @author HP
 */
public class Connexion extends javax.swing.JFrame {

    private UtilisateurDAO userDAO;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Connexion.class.getName());

    /**
     * Creates new form Connexion
     */
    public Connexion() {
        initComponents();
        userDAO = new UtilisateurDAO();
        initUser();

    }

    private void initUser() {
        List<Utilisateurs> userList = userDAO.allUtilisateurs();
        if (userList.isEmpty()) {
            userDAO.createUser(new Utilisateurs("Dieng", "Oumy", "oumydieng@gmail.com", "kalsoume", "123456", Role.GESTIONNAIRE.getValue()));
            userDAO.createUser(new Utilisateurs("Diop", "Mamy", "mamy@gmail.com", "mamy", "123456", Role.CAISSIER.getValue()));

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        motdepasse_txt = new javax.swing.JPasswordField();
        inscrire_btn = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("UserName");

        jLabel3.setText("Mot de passe");

        jButton1.setText("Connexion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        motdepasse_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motdepasse_txtActionPerformed(evt);
            }
        });

        inscrire_btn.setText("S inscrire");
        inscrire_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscrire_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(motdepasse_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inscrire_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(motdepasse_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(inscrire_btn))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void motdepasse_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motdepasse_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motdepasse_txtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

    String userName = username_txt.getText().trim();
    String password = motdepasse_txt.getText().trim();

    Utilisateurs user = userDAO.connexionUser(userName);

    if (user != null &&
        UtilsFonction.decrypt(user.getPassword()).equals(password)) {
              if (!user.getActif()) {
               JOptionPane.showMessageDialog(this,"Votre compte a été désactivé. Veuillez contacter l'administrateur."); 

    return;
}
          if(user.getPremiereConnexion()){

    new ChangerMotDePasseForm(user).setVisible(true);

    this.dispose();

    return;
}
        if (user.getRole().equals(Role.ADMIN.getValue())) {

    JOptionPane.showMessageDialog(this,
            "Je suis Administrateur");

    new AdminFormulaire().setVisible(true);

}
else if (user.getRole().equals(
        Role.GESTIONNAIRE.getValue())) {

    JOptionPane.showMessageDialog(this,
            "Je suis Gestionnaire");

    new Formulaire(user).setVisible(true);

}
else if (user.getRole().equals(
        Role.CAISSIER.getValue())) {

    JOptionPane.showMessageDialog(this,
            "Je suis Caissier");

   new TransactionForm().setVisible(true);

}
        this.dispose();

    } else {

        JOptionPane.showMessageDialog(this,
                "Username ou mot de passe incorrect");

    }

 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inscrire_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscrire_btnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_inscrire_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Connexion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inscrire_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField motdepasse_txt;
    private javax.swing.JTextField username_txt;
    // End of variables declaration//GEN-END:variables
}
