/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import dao.TransactionDAO;
import models.Transactions;
import java.util.List;
import javax.swing.JOptionPane;
import utils.UtilsFonction;
/**
 *
 * @author SOW
 */
public class ListeTransactionsForm extends javax.swing.JFrame {
    private TransactionDAO transactionDAO;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListeTransactionsForm.class.getName());

    /**
     * Creates new form ListeTransactionsForm
     */
    public ListeTransactionsForm() {
        initComponents();
        transactionDAO = new TransactionDAO();

    chargerTransactions();
    }
    private void chargerTransactions(){

    List<Transactions> transactions =
            transactionDAO.allTransaction();

    UtilsFonction.displayDataInTable(
            transactions,
            transactionTable
    );
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        retour_btn = new javax.swing.JButton();
        filtre_cbx = new javax.swing.JComboBox<>();
        filtrer_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LISTE DES TRANSACTIONS");

        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(transactionTable);

        retour_btn.setText("RETOUR");
        retour_btn.addActionListener(this::retour_btnActionPerformed);

        filtre_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tous", "Aujourd'hui", "Semaine courante", "Mois courant", "6 derniers mois", "Année courante" }));
        filtre_cbx.addActionListener(this::filtre_cbxActionPerformed);

        filtrer_btn.setText("FILTRER");
        filtrer_btn.addActionListener(this::filtrer_btnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filtrer_btn)
                            .addComponent(filtre_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(retour_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(filtre_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(filtrer_btn)
                .addGap(61, 61, 61)
                .addComponent(retour_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retour_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retour_btnActionPerformed
        // TODO add your handling code here:
        new AdminFormulaire().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_retour_btnActionPerformed

    private void filtre_cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtre_cbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtre_cbxActionPerformed

    private void filtrer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrer_btnActionPerformed
        // TODO add your handling code here:
       
        String filtre =
        filtre_cbx.getSelectedItem().toString();

if(filtre.equals("Tous")){

    chargerTransactions();
}
if(filtre.equals("Aujourd'hui")){
    JOptionPane.showMessageDialog(
        null,
        transactionDAO.transactionsAujourdhui().size()
);

    UtilsFonction.displayDataInTable(
            transactionDAO.transactionsAujourdhui(),
            transactionTable
    );
}
if(filtre.equals("Année courante")){

    UtilsFonction.displayDataInTable(
            transactionDAO.transactionsAnneeCourante(),
            transactionTable
    );
}
if(filtre.equals("Mois courant")){

    UtilsFonction.displayDataInTable(
            transactionDAO.transactionsMoisCourant(),
            transactionTable
    );
}
if(filtre.equals("Semaine courante")){

    UtilsFonction.displayDataInTable(
            transactionDAO.transactionsSemaineCourante(),
            transactionTable
    );
}
if(filtre.equals("6 derniers mois")){

    UtilsFonction.displayDataInTable(
            transactionDAO.transactionsSixDerniersMois(),
            transactionTable
    );
}
    }//GEN-LAST:event_filtrer_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListeTransactionsForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> filtre_cbx;
    private javax.swing.JButton filtrer_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton retour_btn;
    private javax.swing.JTable transactionTable;
    // End of variables declaration//GEN-END:variables
}
