/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.CompteDAO;
import dao.TransactionDAO;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import models.Comptes;
/**
 *
 * @author SOW
 */
public class TransactionForm extends javax.swing.JFrame {
    private TransactionDAO transactionDAO = new TransactionDAO();
    private CompteDAO compteDAO = new CompteDAO();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransactionForm.class.getName());

    /**
     * Creates new form TransactionForm
     */
    public TransactionForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        compteSource_txt = new javax.swing.JTextField();
        compteDestination_txt = new javax.swing.JTextField();
        montant_txt = new javax.swing.JTextField();
        typeTransaction_cbx = new javax.swing.JComboBox<>();
        valider_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Compte Source");

        jLabel2.setText("Compte Destination");

        jLabel3.setText("Montant");

        jLabel4.setText("Type Transaction");

        typeTransaction_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "depot", "retrait", "virment" }));
        typeTransaction_cbx.addActionListener(this::typeTransaction_cbxActionPerformed);

        valider_btn.setText("VALIDER");
        valider_btn.addActionListener(this::valider_btnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(compteSource_txt)
                    .addComponent(compteDestination_txt)
                    .addComponent(montant_txt)
                    .addComponent(typeTransaction_cbx, 0, 148, Short.MAX_VALUE))
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(valider_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compteSource_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compteDestination_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(montant_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeTransaction_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(valider_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeTransaction_cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeTransaction_cbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeTransaction_cbxActionPerformed

    private void valider_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valider_btnActionPerformed
        // TODO add your handling code here:
        String numeroSource = compteSource_txt.getText().trim();
    String numeroDestination = compteDestination_txt.getText().trim();

    BigDecimal montant =
            new BigDecimal(montant_txt.getText());

    String type =
            typeTransaction_cbx.getSelectedItem().toString();

    Comptes source =
            compteDAO.rechercheCompte(numeroSource);

    if (source == null) {
        JOptionPane.showMessageDialog(null,"Compte source  bi c est introuvable");
        return;
    }

    if (type.equals("depot")) {

        transactionDAO.depot(source, montant);

        JOptionPane.showMessageDialog(null," Sa Depot bi dialleuh na");
    }

    if (type.equals("retrait")) {

        boolean ok =
                transactionDAO.retrait(source, montant);

        if (ok) {
            JOptionPane.showMessageDialog(null,"Sa retrait demeuh na akk diam");
        } else {
            JOptionPane.showMessageDialog(null,"Solde bi kholatt ko c est  insuffisant");
        }
    }

    if (type.equals("virment")) {

        Comptes destination =
                compteDAO.rechercheCompte(numeroDestination);

        if (destination == null) {
            JOptionPane.showMessageDialog(null,
                    "Compte destination introuvable");
            return;
        }

        boolean ok =
                transactionDAO.virement(
                        source,
                        destination,
                        montant);

        if (ok) {
            JOptionPane.showMessageDialog(null, "Virement bi  demmeuh na ");
        } else {
            JOptionPane.showMessageDialog(null, "Solde insuffisant");
        }
    }
    }//GEN-LAST:event_valider_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TransactionForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField compteDestination_txt;
    private javax.swing.JTextField compteSource_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField montant_txt;
    private javax.swing.JComboBox<String> typeTransaction_cbx;
    private javax.swing.JButton valider_btn;
    // End of variables declaration//GEN-END:variables
}
